-- MySQL Script generated by MySQL Workbench
-- 05/20/17 17:14:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mola
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mola` DEFAULT CHARACTER SET latin1 ;
USE `mola` ;

-- -----------------------------------------------------
-- Table `mola`.`Language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mola`.`Language` (
  `Name` VARCHAR(200) NULL,
  `ID` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mola`.`Learner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mola`.`Learner` (
  `ID` INT NOT NULL,
  `Email` VARCHAR(200) NULL,
  `Password` VARCHAR(45) NULL,
  `FirstName` NVARCHAR(45) NULL,
  `LastName` NVARCHAR(45) NULL,
  `FacebookID` VARCHAR(200) NULL,
  `GoogleID` VARCHAR(200) NULL,
  `Avatar` VARCHAR(500) NULL,
  `LanguageSpeak` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Learner_Language1_idx` (`LanguageSpeak` ASC),
  CONSTRAINT `fk_Learner_Language1`
    FOREIGN KEY (`LanguageSpeak`)
    REFERENCES `mola`.`Language` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mola`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mola`.`Teacher` (
  `ID` INT NOT NULL,
  `ExpYears` INT NULL,
  `ExpDescription` TEXT NULL,
  `Introduction` TEXT NULL,
  `IntroClip` VARCHAR(200) NULL,
  `NumOfRate` INT NULL,
  `Rating` FLOAT NULL,
  `Teachercol` VARCHAR(45) NULL,
  `Learner_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Teacher_Learner1_idx` (`Learner_ID` ASC),
  CONSTRAINT `fk_Teacher_Learner1`
    FOREIGN KEY (`Learner_ID`)
    REFERENCES `mola`.`Learner` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mola`.`LanguageLearn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mola`.`LanguageLearn` (
  `ID` INT NOT NULL,
  `Language_ID` INT NOT NULL,
  `Learner_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Language_ID`, `Learner_ID`),
  INDEX `fk_LanguageLearn_Language1_idx` (`Language_ID` ASC),
  INDEX `fk_LanguageLearn_Learner1_idx` (`Learner_ID` ASC),
  CONSTRAINT `fk_LanguageLearn_Language1`
    FOREIGN KEY (`Language_ID`)
    REFERENCES `mola`.`Language` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LanguageLearn_Learner1`
    FOREIGN KEY (`Learner_ID`)
    REFERENCES `mola`.`Learner` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mola`.`LanguageTeach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mola`.`LanguageTeach` (
  `ID` INT NOT NULL,
  `Teacher_ID` INT NOT NULL,
  `Language_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Teacher_ID`, `Language_ID`),
  INDEX `fk_LanguageTeach_Teacher1_idx` (`Teacher_ID` ASC),
  INDEX `fk_LanguageTeach_Language1_idx` (`Language_ID` ASC),
  CONSTRAINT `fk_LanguageTeach_Teacher1`
    FOREIGN KEY (`Teacher_ID`)
    REFERENCES `mola`.`Teacher` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LanguageTeach_Language1`
    FOREIGN KEY (`Language_ID`)
    REFERENCES `mola`.`Language` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mola`.`RatingTeacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mola`.`RatingTeacher` (
  `ID` INT NOT NULL,
  `Rating` INT NULL,
  `Teacher_ID` INT NOT NULL,
  `Learner_ID` INT NOT NULL,
  `Comment` TEXT NULL,
  PRIMARY KEY (`ID`, `Teacher_ID`, `Learner_ID`),
  INDEX `fk_Rating_Teacher1_idx` (`Teacher_ID` ASC),
  INDEX `fk_Rating_Learner1_idx` (`Learner_ID` ASC),
  CONSTRAINT `fk_Rating_Teacher1`
    FOREIGN KEY (`Teacher_ID`)
    REFERENCES `mola`.`Teacher` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rating_Learner1`
    FOREIGN KEY (`Learner_ID`)
    REFERENCES `mola`.`Learner` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mola`.`TimeSlot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mola`.`TimeSlot` (
  `ID` INT NOT NULL,
  `StarTime` DATETIME NULL,
  `EndTime` DATETIME NULL,
  `Teacher_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_TimeSlot_Teacher1_idx` (`Teacher_ID` ASC),
  CONSTRAINT `fk_TimeSlot_Teacher1`
    FOREIGN KEY (`Teacher_ID`)
    REFERENCES `mola`.`Teacher` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mola`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mola`.`Course` (
  `ID` INT NOT NULL,
  `Title` NVARCHAR(45) NULL,
  `Introduction` TEXT NULL,
  `Structured` TINYINT(1) NULL,
  `Coursecol` VARCHAR(45) NULL,
  `Teacher_ID` INT NOT NULL,
  `NumOfRate` INT NULL,
  `Rating` FLOAT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Course_Teacher1_idx` (`Teacher_ID` ASC),
  CONSTRAINT `fk_Course_Teacher1`
    FOREIGN KEY (`Teacher_ID`)
    REFERENCES `mola`.`Teacher` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mola`.`Chapter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mola`.`Chapter` (
  `ID` INT NOT NULL,
  `Title` NVARCHAR(200) NULL,
  `Number` NVARCHAR(200) NULL,
  `Chaptercol` VARCHAR(45) NULL,
  `Course_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Chapter_Course1_idx` (`Course_ID` ASC),
  CONSTRAINT `fk_Chapter_Course1`
    FOREIGN KEY (`Course_ID`)
    REFERENCES `mola`.`Course` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mola`.`Lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mola`.`Lesson` (
  `ID` INT NOT NULL,
  `Description` TEXT NULL,
  `Title` NVARCHAR(200) NULL,
  `Lessoncol1` VARCHAR(45) NULL,
  `Chapter_ID` INT NOT NULL,
  `UnstructureCourse_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Lesson_Chapter1_idx` (`Chapter_ID` ASC),
  INDEX `fk_Lesson_Course1_idx` (`UnstructureCourse_ID` ASC),
  CONSTRAINT `fk_Lesson_Chapter1`
    FOREIGN KEY (`Chapter_ID`)
    REFERENCES `mola`.`Chapter` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lesson_Course1`
    FOREIGN KEY (`UnstructureCourse_ID`)
    REFERENCES `mola`.`Course` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mola`.`RatingCourse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mola`.`RatingCourse` (
  `ID` INT NOT NULL,
  `Rating` INT NULL,
  `Comment` TEXT NULL,
  `Course_ID` INT NOT NULL,
  `Learner_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Course_ID`, `Learner_ID`),
  INDEX `fk_RatingCourse_Course1_idx` (`Course_ID` ASC),
  INDEX `fk_RatingCourse_Learner1_idx` (`Learner_ID` ASC),
  CONSTRAINT `fk_RatingCourse_Course1`
    FOREIGN KEY (`Course_ID`)
    REFERENCES `mola`.`Course` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RatingCourse_Learner1`
    FOREIGN KEY (`Learner_ID`)
    REFERENCES `mola`.`Learner` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mola`.`Session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mola`.`Session` (
  `ID` INT NOT NULL,
  `TimeSlot_ID` INT NOT NULL,
  `Learner_ID` INT NOT NULL,
  `Lesson_ID` INT NOT NULL,
  `Status` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`, `TimeSlot_ID`, `Learner_ID`, `Lesson_ID`),
  INDEX `fk_Session_TimeSlot1_idx` (`TimeSlot_ID` ASC),
  INDEX `fk_Session_Learner1_idx` (`Learner_ID` ASC),
  INDEX `fk_Session_Lesson1_idx` (`Lesson_ID` ASC),
  CONSTRAINT `fk_Session_TimeSlot1`
    FOREIGN KEY (`TimeSlot_ID`)
    REFERENCES `mola`.`TimeSlot` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Session_Learner1`
    FOREIGN KEY (`Learner_ID`)
    REFERENCES `mola`.`Learner` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Session_Lesson1`
    FOREIGN KEY (`Lesson_ID`)
    REFERENCES `mola`.`Lesson` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mola`.`RegisterCourse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mola`.`RegisterCourse` (
  `ID` INT NOT NULL,
  `Course_ID` INT NOT NULL,
  `Learner_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Course_ID`, `Learner_ID`),
  INDEX `fk_RegisterCourse_Course1_idx` (`Course_ID` ASC),
  INDEX `fk_RegisterCourse_Learner1_idx` (`Learner_ID` ASC),
  CONSTRAINT `fk_RegisterCourse_Course1`
    FOREIGN KEY (`Course_ID`)
    REFERENCES `mola`.`Course` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RegisterCourse_Learner1`
    FOREIGN KEY (`Learner_ID`)
    REFERENCES `mola`.`Learner` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
